language: haskell
ghc: 7.6.3
install:
  - "cabal update"
  - "cabal install purescript --force-reinstalls"
  - "npm install bower grunt-cli -g"
  - "npm install"
  - "bower install"
script:
    - "grunt test"
